### ISSUE TITLE
[Performance] RealisticSeaons tooks too much tick time to unfreeze the chunks

### ISSUE THREAD

**Issue by Ghost-chu** [casperge/RealisticSeasons-issues#104] opened 2022-01-15 14:09 UTC
Spark sampler report:
https://spark.lucko.me/id2umjaaHs

While server have ton of chunks loaded, RS will run unfreeze task intervaly and create a heavy lag spike, and player can notice that.

The question is not only it slow heavy, but also frequently.

That's really hurt the game experenice.

**Comment by casperge** [comment] 2022-01-17 10:36
Hey Ghost-chu. Thank you for the spark report, it helps a lot. I will look into this and I would advise changing "delay-per-operation" in the config.yml to at least 10. This will slow down the plugin a bit and improve performance.

**Comment by Ghost-chu** [comment] 2022-01-17 10:47
> Hey Ghost-chu. Thank you for the spark report, it helps a lot. I will look into this and I would advise changing "delay-per-operation" in the config.yml to at least 10. This will slow down the plugin a bit and improve performance.

I think the question is the [Spring/Summer/Fall] ticker will scan over 7k+ chunks on my busy server in single tick.

The most worst thing, it will loading chunks while scanning them.

I'm sorry but I have use Recaf to checked the plugin code, because it can make server TPS drop to 4-7 tps from 20 and create a crazy lag spike. In certain circumstances, it even can active the Spigot Watchdog to dump threads.

I also noticed RS use `Chunk#isChunkLoaded` method to check if chunks has been loaded.
But this chunk is created by use `getChunkAt` method which it behavior has been changed since CB 1.13+ and it will force loading chunks if it unloaded, so I prefer use `World#isChunkLoaded(X,Z)`. And I guess that's why I can see RS trying loading chunks in my other spark reports.

**Comment by casperge** [comment] 2022-01-17 11:00
The [Spring/Summer/Fall] ticker has a queue of chunks that haven't been updated yet and the runnable will choose one chunk each x ticks (depends on delay-per-operation). Scanning 7k+ chunks would definitely result in a crash. Also use my own object (SeasonChunk) instead of Chunk to limit memory usage and lag caused by big arrays.  

One chunk per tick and a maximum of ~40 blocks a second should not be able to cause lag. Chunk loading however could.

Feel free to read through my code, you paid for it. Especially in these situations, help is always appreciated! I think the issue is indeed me using the wrong function. I wasn't aware that this would load the chunk. I will fix this today with an update, thank you for you help!

**Comment by casperge** [comment] 2022-01-17 13:45
Fixed in v7.13 releasing later today.

**Closed as completed by casperge** 2022-01-17 13:45 UTC
Labels: bug
